# Log rotation configuration for Minecraft server logs
/minecraft/logs/*.log {
    rotate 5
    daily
    missingok
    notifempty
    size 25M
    compress
    delaycompress
    copytruncate
    create 640 minecraft minecraft
}

# Samba log rotation
/var/log/samba/*.log {
    rotate 5
    daily
    missingok
    notifempty
    size 25M
    compress
    delaycompress
    create 640 root root
}

# MySQL log rotation
/var/log/supervisor/mysql*.log {
    rotate 5
    daily
    missingok
    notifempty
    size 25M
    compress
    delaycompress
    create 640 root root
}
