modLoader="javafml"
loaderVersion="[44,]"
license="GNU GENERAL PUBLIC LICENSE Version 3"

[[mods]]
    modId="netherdeck"
    version="${version}"
    displayName="NetherDeck"
    displayTest="IGNORE_SERVER_VERSION"
    credits="lona,夜幕,IzzelAliz (NetherDeck),Paper Team"
    authors="DownUnderIT Solutions"
    description='''
    NetherDeck - Paper-performance Forge+Bukkit hybrid server (based on NetherDeck)
    '''
